version: '3.9'

services:
  db:
    container_name: db
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
    volumes:
      - my-db:/var/lib/mysql

volumes:
  my-db: {}